version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse

    steps:
      - checkout

      - run:
          name: Run the file
          command: |
             R -q -e "install.packages(c('rmarkdown','flexdashboard'))" |  
             R -q -e "rmarkdown::render('index.Rmd',output_file='index.html')"
